# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: lina
email: acsd@ufpi.edu.br
description: > # this means to ignore newlines until "baseurl:"
  Just a small techy blog focused on Design, HCI, and foreign languages.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://linasdias.github.io" # the base hostname & protocol for your site
twitter_username: hi_its_lina
github_username:  linasdias
instagram_username: acsdyeux

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname: lina-5

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
